name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add current user to docker group and refresh session
        run: |
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Build the Docker image
        run: docker build -t secure-file-transfer .

      - name: Deploy the container
        run: |
          ssh -o StrictHostKeyChecking=no -i ./id_rsa ubuntu@${{ secrets.ORACLE_CLOUD_IP }} << EOF
            # Ensure the directory exists
            #mkdir -p /home/ubuntu/secure-file-transfer
            git clone https://github.com/aman25502/secure-file-transfer secure-file-transfer
            cd /home/ubuntu/secure-file-transfer

            # Stop and remove any existing container
            sudo docker stop secure-file-transfer || true
            sudo docker rm secure-file-transfer || true

            # Run the new container
            sudo docker run -d -p 8080:8080 --name secure-file-transfer secure-file-transfer
          EOF
