name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Oracle Cloud
        run: |
          ssh -o StrictHostKeyChecking=no -i ./id_rsa ubuntu@${{ secrets.ORACLE_CLOUD_IP }} << EOF
            # Ensure the directory exists and navigate to it
            mkdir -p /home/ubuntu/secure-file-transfer
            cd /home/ubuntu/secure-file-transfer

            # Clone the repository if it doesn't already exist
            if [ ! -d ".git" ]; then
              git clone https://github.com/aman25502/secure-file-transfer .
              git pull origin main
            fi

            # Build the Docker image
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo docker build -t secure-file-transfer .

            # Stop and remove any existing container
            sudo docker stop secure-file-transfer || true
            sudo docker rm secure-file-transfer || true

            # Run the new container
            sudo docker run -d -p 8080:8080 --name secure-file-transfer secure-file-transfer
          EOF
