name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up SSH key
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add current user to docker group and refresh session
      run: |
        sudo usermod -aG docker $USER
        newgrp docker

    # Step 3: Deploy to Oracle Cloud Instance
    - name: Deploy to Oracle Cloud
      env:
        ORACLE_CLOUD_INSTANCE_IP: ${{ secrets.ORACLE_CLOUD_INSTANCE_IP }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ./id_rsa ubuntu@${{ secrets.ORACLE_CLOUD_INSTANCE_IP }} << EOF
          # Create project directory if it doesn't exist
          mkdir -p ~/secure-file-transfer
          cd ~/secure-file-transfer

          # Clone or update the repo
          if [ ! -d .git ]; then
            git clone https://github.com/aman25502/secure-file-transfer.git .
          else
            git pull
          fi

          # Install Docker if not already installed
          if ! command -v docker &> /dev/null
          then
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi

          # Build the Docker image and deploy the application
          docker stop $(docker ps -q --filter ancestor=secure-file-transfer) || true
          docker build -t secure-file-transfer .
          docker run -d -p 80:8080 secure-file-transfer
        EOF
